// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The offlinecv Authors

/**
 * Value-locking regression for #843 item 5 — `looksLikeHeaderlessRoleHeader`'s
 * `INSTITUTION_HINTS` guard (`sections.ts`, guard 5) rejecting real,
 * institution-named EMPLOYERS out of the headerless-experience recovery
 * (#492), because it tested the hint un-anchored over the WHOLE head instead
 * of the head's lead segment the way the degree half already anchors.
 *
 * `tests/fixtures/pdfs/unknown/headerless-experience-institution-employer.pdf`
 * (generated by `scripts/fixtures/gen-headerless-experience-institution-employer.mjs`)
 * is the same headerless-work-history shape as `headerless-experience.pdf`
 * (#492), except two of its three cluster roles work at
 * `INSTITUTION_HINTS`-bearing employers — "Stanford University", "Khan
 * Academy" — in the EMPLOYER segment, after the comma. Before the fix, both
 * failed `looksLikeHeaderlessRoleHeader` exactly like an unheadered EDUCATION
 * entry would, only the third (ordinary-employer) role passed on its own, the
 * cluster never reached `HEADERLESS_ROLE_CLUSTER_MIN` on institution-named
 * members alone, and this fixture's whole work history was dropped:
 * `experienceCount: 0`. After the fix all three roles recover.
 *
 * Persona is synthetic (Riley Chen / riley.chen@example.com), per the
 * fixtures PII policy — no real-person data.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, it, expect, beforeAll } from "vitest";
import { runCascade } from "./cascade.ts";
import type { CascadeResult } from "./types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(
  HERE,
  "../../..",
  "tests/fixtures/pdfs/unknown/headerless-experience-institution-employer.pdf",
);

describe("institution-named employers still recover in a headerless work history (#843)", () => {
  let cascade: CascadeResult;

  beforeAll(async () => {
    const bytes = readFileSync(FIXTURE);
    cascade = await runCascade(new Uint8Array(bytes));
  });

  it("parses every role — the reported defect was zero", () => {
    expect(cascade.canonical.fields.experience ?? []).toHaveLength(3);
  });

  it("recovers the institution-named employers, not just the ordinary one", () => {
    const companies = (cascade.canonical.fields.experience ?? []).map((r) => r.company);
    expect(companies).toEqual(["Stanford University", "Khan Academy", "Northwind Systems"]);
  });

  it("does not swallow the EDUCATION entry below its own header", () => {
    expect(cascade.canonical.fields.education ?? []).toHaveLength(1);
    const region = cascade.canonical.sections.byName.get("experience") ?? [];
    expect(region.some((l) => l.includes("Ridgemont State"))).toBe(false);
  });

  it("dates every recovered role", () => {
    const roles = cascade.canonical.fields.experience ?? [];
    expect(
      roles.map((r) => [r.start_date ?? null, r.end_date ?? (r.is_current ? "Present" : null)]),
    ).toEqual([
      ["Sep 2018", "Jun 2021"],
      ["Jul 2021", "Present"],
      ["Feb 2016", "Aug 2018"],
    ]);
  });
});
